name: Auto-Deploy Streamlit App

on:
  push:
    branches:
      - main  # Runs when changes are pushed to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu machine

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Use the required Python version

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Streamlit App
        run: |
          nohup streamlit run app.py --server.port=8501 &
